name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests browser_cookie3
    - name: Build
      run: pyinstaller --noconsole --onefile --icon=icon.ico --name="Calculadora_Profit_DiosesMC" main.py
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Programa_Final
        path: dist/Calculadora_Profit_DiosesMC.exe
